// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSYgBvw9ZGhU_czB2S61EnY36inra4K7U',
    appId: '1:1089166856679:android:37e16895a6ef709efaad42',
    messagingSenderId: '1089166856679',
    projectId: 'helpdesk-b3809',
    storageBucket: 'helpdesk-b3809.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtZvjjE3zWiIPTPg3sfPbleobEQGPvU3k',
    appId: '1:1089166856679:ios:f81e0a4e2fbd258bfaad42',
    messagingSenderId: '1089166856679',
    projectId: 'helpdesk-b3809',
    storageBucket: 'helpdesk-b3809.firebasestorage.app',
    iosBundleId: 'com.example.helpdesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6YY8SRyroj6sAQzZOmXQj9eVBbYQ_uMg',
    appId: '1:1089166856679:web:ff26f198e3630c7bfaad42',
    messagingSenderId: '1089166856679',
    projectId: 'helpdesk-b3809',
    authDomain: 'helpdesk-b3809.firebaseapp.com',
    storageBucket: 'helpdesk-b3809.firebasestorage.app',
    measurementId: 'G-N82MFXKCWP',
  );
}
